import { Geist, Geist_Mono } from "next/font/google";
import "antd/dist/reset.css";
import "./globals.css";
import { AppProviders } from "@/providers/AppProviders";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ZK-vote",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  function readEnvLocalFallback() {
    // 中文说明：某些情况下（例如 Turbopack/进程环境变量）可能导致 process.env 读不到 .env.local 的值
    // 这里作为兜底，直接读取 frontend/.env.local 并解析 NEXT_PUBLIC_* 配置。
    try {
      // 中文说明：不要只依赖 process.cwd()，Next/Turbopack 可能改变工作目录。
      // 这里用当前文件绝对路径推导 frontend 根目录，再读取 frontend/.env.local。
      var __filename = fileURLToPath(import.meta.url);
      var __dirname = path.dirname(__filename);
      var frontendRoot = path.join(__dirname, "..");

      var cwd = process.cwd();
      var candidatePaths = [
        path.join(cwd, ".env.local"),
        path.join(cwd, "frontend", ".env.local"),
        path.join(frontendRoot, ".env.local"),
      ];

      var envPath = "";
      for (var p = 0; p < candidatePaths.length; p++) {
        if (fs.existsSync(candidatePaths[p])) {
          envPath = candidatePaths[p];
          break;
        }
      }

      if (!envPath) return {};

      var text = fs.readFileSync(envPath, "utf8");
      var lines = text.split(/\r?\n/);
      var result = {};

      for (var i = 0; i < lines.length; i++) {
        var line = lines[i];
        if (!line) continue;
        if (line.trim().startsWith("#")) continue;
        var idx = line.indexOf("=");
        if (idx === -1) continue;
        var key = line.slice(0, idx).trim();
        var value = line.slice(idx + 1).trim();
        if (key.startsWith("NEXT_PUBLIC_")) {
          result[key] = value;
        }
      }

      return result;
    } catch (e) {
      return {};
    }
  }

  var fileEnv = readEnvLocalFallback();
  const runtimeEnv = {
    NEXT_PUBLIC_BACKEND_BASE_URL:
      process.env.NEXT_PUBLIC_BACKEND_BASE_URL ||
      fileEnv.NEXT_PUBLIC_BACKEND_BASE_URL ||
      "",
    NEXT_PUBLIC_CHAIN_ID:
      process.env.NEXT_PUBLIC_CHAIN_ID || fileEnv.NEXT_PUBLIC_CHAIN_ID || "",
    NEXT_PUBLIC_PARTY_VOTING_ADDRESS:
      process.env.NEXT_PUBLIC_PARTY_VOTING_ADDRESS ||
      fileEnv.NEXT_PUBLIC_PARTY_VOTING_ADDRESS ||
      "",
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <script
          dangerouslySetInnerHTML={{
            __html: `window.__APP_ENV__=${JSON.stringify(runtimeEnv)};`,
          }}
        />
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
